# -*- coding: utf-8 -*-
"""Untitled73.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieiCw-X93ugNWqu_hM-wkFfE79pK0Rc4
"""

pip install firebase-admin

import pandas as pd
import numpy as np
import firebase_admin
from firebase_admin import credentials, firestore

# === Safe Firebase Initialization ===
if not firebase_admin._apps:
    cred = credentials.Certificate("/content/athlon-c08aa-firebase-adminsdk-fbsvc-d9efc7cbe4.json")
    firebase_admin.initialize_app(cred)
db = firestore.client()

def upload_all_metrics(
    passes_csv, aerial_csv, ground_csv, interceptions_csv, tackles_csv, dribble_csv,
    set_pieces_csv, goals_csv, shots_csv, pass_network_csv,
    match_id,
    first_team_id="team1",
    second_team_id="team2"
):
    # === PASSES ===
    df_passes = pd.read_csv(passes_csv)
    df_passes[['position_x', 'position_y']] = pd.DataFrame(df_passes['position'].apply(eval).tolist(), index=df_passes.index)
    team_id_field = "team_id_1" if "team_id_1" in df_passes.columns else "team_id"

    passes_dict = {}
    for idx, row in df_passes.iterrows():
        team = first_team_id if row[team_id_field] == 1 else second_team_id
        passes_dict[str(idx)] = {
            "start_timestamp": int(row['start_frame_num']),
            "end_timestamp": int(row['end_frame_num']),
            "position_x": float(row['position_x']),
            "position_y": float(row['position_y']),
            "shirt_number": int(row['shirt_num1']),
            "success": row['success'] == 1 and row['fail'] == 0,
            "team_id": team
        }

    # === DUEL HELPER ===
    def process_duel(csv_path, success_col, fail_col, team_col_guess, shirt_col_guess, drop_condition=None):
        df = pd.read_csv(csv_path)
        df[['position_x', 'position_y']] = pd.DataFrame(df['position'].apply(eval).tolist(), index=df.index)
        team_col = team_col_guess if team_col_guess in df.columns else "team_id"
        shirt_col = shirt_col_guess if shirt_col_guess in df.columns else "shirt_number"
        if drop_condition:
            df = df[~drop_condition(df)]
        duel_dict = {}
        for idx, row in df.iterrows():
            team = first_team_id if row[team_col] == 1 else second_team_id
            success = row[success_col] == 1 and row[fail_col] == 0
            duel_dict[str(idx)] = {
                "start_timestamp": int(row['start_frame_num']),
                "end_timestamp": int(row['end_frame_num']),
                "position_x": float(row['position_x']),
                "position_y": float(row['position_y']),
                "shirt_number": int(row[shirt_col]),
                "success": success,
                "team_id": team
            }
        return duel_dict

    # === DUELS ===
    duels = {
        "aerial": process_duel(aerial_csv, "aerial_success", "aerial_failure", "team_id", "shirt_number"),
        "ground": process_duel(ground_csv, "ground_success", "ground_failure", "team_id", "shirt_number"),
        "interceptions": process_duel(interceptions_csv, "ball_recovery", "ball_loss", "team_id", "shirt_number"),
        "tackles": process_duel(tackles_csv, "tackling_success", "tackling_failure", "team_id", "shirt_number"),
        "dribbles": process_duel(dribble_csv, "dribble_success", "dribble_failure", "team_id_1", "shirt_number_1", drop_condition=lambda df: df["dribbled_past"] == 1)
    }

    # === SET PIECES ===
    df_set = pd.read_csv(set_pieces_csv)
    df_set[['position_x', 'position_y']] = pd.DataFrame(df_set['position'].apply(eval).tolist(), index=df_set.index)
    set_pieces_dict = {}
    for idx, row in df_set.iterrows():
        team = first_team_id if row["team_id_1"] == 1 else second_team_id
        if row['corner'] == 1: typ = 1
        elif row['throw'] == 1: typ = 2
        elif row['direct kick'] == 1: typ = 3
        elif row['indirect kick'] == 1: typ = 4
        elif row['penalty'] == 1: typ = 5
        else: continue
        set_pieces_dict[str(idx)] = {
            "start_timestamp": int(row['start_frame_num']),
            "end_timestamp": int(row['end_frame_num']),
            "position_x": float(row['position_x']),
            "position_y": float(row['position_y']),
            "shirt_number": int(row['shirt_num1']),
            "team_id": team,
            "type": typ
        }

    # === GOALS ===
    df_goals = pd.read_csv(goals_csv)
    if "position" not in df_goals.columns:
        df_goals["position"] = list(zip(df_goals["position_x"], df_goals["position_y"]))
    goals_dict = {}
    for idx, row in df_goals.iterrows():
        team = first_team_id if row["team_id"] == 0 else second_team_id
        goals_dict[str(idx)] = {
            "start_timestamp": max(0, int(row["start_frame_num"])),
            "end_timestamp": max(0, int(row["end_frame_num"])),
            "position_x": float(eval(row["position"])[0]),
            "position_y": float(eval(row["position"])[1]),
            "shirt_number": int(row["shirt_number"]),
            "type": 1 if row["Goal"] == 1 and row["Assist"] == 0 else 2,
            "team_id": team
        }

    # === SHOTS ===
    df_shots = pd.read_csv(shots_csv)
    if "position" not in df_shots.columns:
        df_shots["position"] = list(zip(df_shots["position_x"], df_shots["position_y"]))
    shots_dict = {}
    for idx, row in df_shots.iterrows():
        team = first_team_id if row["team_id"] == 0 else second_team_id
        shots_dict[str(idx)] = {
            "start_timestamp": max(0, int(row["start_frame_num"])),
            "end_timestamp": max(0, int(row["end_frame_num"])),
            "position_x": float(eval(row["position"])[0]),
            "position_y": float(eval(row["position"])[1]),
            "shirt_number": int(row["shirt_number"]),
            "type": 2 if row["Key_passes"] == 1 else 1,
            "success": row["Shots_on_Target"] == 1 and row["Shots_off_Target"] == 0,
            "team_id": team
        }

    # === PASS NETWORK ===
    df_network = pd.read_csv(pass_network_csv)
    network_dict = {}
    for idx, row in df_network.iterrows():
        shirts_raw = row["shirt_number"]
        shirts = eval(shirts_raw) if isinstance(shirts_raw, str) else shirts_raw
        pass_string = [f"{i} {int(shirts[i])}" for i in range(len(shirts))]

        network_dict[str(idx)] = {
            "start_timestamp": max(0, int(row["start_frame_num"])),
            "end_timestamp": max(0, int(row["end_frame_num"])),
            "pass_count": int(row["number_of_passes"]),
            "position_x": float(row["position_x"]),
            "position_y": float(row["position_y"]),
            "pass_string": pass_string
        }

    # === UPLOAD TO FIRESTORE ===
    match_ref = db.collection("match_analytics").document(match_id)
    match_ref.set({
        "distribution": {
            "passes": passes_dict,
            "pass_network": network_dict
        },
        "duels": duels,
        "set_pieces": set_pieces_dict,
        "goals": goals_dict,
        "shots": shots_dict
    }, merge=True)

    print("✅ All metrics uploaded successfully .")
upload_all_metrics(
    passes_csv="/content/passes_metrics.csv",
    aerial_csv="/content/aerial_duels_fixed.csv",
    ground_csv="/content/ground_duels_fixed.csv",
    interceptions_csv="/content/interceptions_metrics_fixed.csv",
    tackles_csv="/content/tackles_metrics.csv",
    dribble_csv="/content/dribble_metrics_success_only.csv",
    set_pieces_csv="/content/set_pieces_metrics.csv",
    goals_csv="/content/goals_metrics_fixed.csv",
    shots_csv="/content/shots_metrics_fixed.csv",
    pass_network_csv="/content/passing_network_metrics.csv",
    match_id="mIPqSIphxFeeix2gKpbB",
    first_team_id="VVC#214",
    second_team_id="DRC#334"
)

import pandas as pd
import firebase_admin
from firebase_admin import credentials, firestore

# === Initialize Firebase ===
if not firebase_admin._apps:
    cred = credentials.Certificate("/content/athlon-c08aa-firebase-adminsdk-fbsvc-d9efc7cbe4.json")
    firebase_admin.initialize_app(cred)
db = firestore.client()

def upload_match_summary(
    match_id,
    first_team_id,
    second_team_id,
    passes_csv,
    set_pieces_csv,
    shots_csv,
    tackles_csv,
    goals_csv
):
    # === Load CSVs
    df_passes = pd.read_csv(passes_csv)
    df_set = pd.read_csv(set_pieces_csv)
    df_shots = pd.read_csv(shots_csv)
    df_tackles = pd.read_csv(tackles_csv)
    df_goals = pd.read_csv(goals_csv)

    def get_team_name(val): return first_team_id if val in [1, '1'] else second_team_id

    # === ✅ Passes & Possession: only successful passes
    df_passes = df_passes[(df_passes['success'] == 1) & (df_passes['fail'] == 0)]
    df_passes['team'] = df_passes['team_id_1'].apply(get_team_name)
    total_passes = len(df_passes)
    passes = df_passes['team'].value_counts().to_dict()
    ball_possession = {
        first_team_id: round((passes.get(first_team_id, 0) / total_passes) * 100) if total_passes else 0,
        second_team_id: round((passes.get(second_team_id, 0) / total_passes) * 100) if total_passes else 0
    }

    # === Shirt Numbers (use all passes)
    df_all_passes = pd.read_csv(passes_csv)
    df_all_passes['team'] = df_all_passes['team_id_1'].apply(get_team_name)
    shirt_numbers = {
        first_team_id: sorted(df_all_passes[df_all_passes['team'] == first_team_id]['shirt_num1'].dropna().astype(int).unique().tolist()),
        second_team_id: sorted(df_all_passes[df_all_passes['team'] == second_team_id]['shirt_num1'].dropna().astype(int).unique().tolist())
    }

    # === Corners & Free Kicks
    df_set['team'] = df_set['team_id_1'].apply(get_team_name)
    corners = df_set[df_set['corner'] == 1]['team'].value_counts().to_dict()
    free_kicks = df_set[(df_set['direct kick'] == 1) | (df_set['indirect kick'] == 1)]['team'].value_counts().to_dict()

    # === ✅ Shots: dynamic team mapping
    shot_teams = df_shots['team_id'].unique()
    if len(shot_teams) == 2:
        shot_map = {shot_teams[0]: first_team_id, shot_teams[1]: second_team_id}
    else:
        shot_map = {shot_teams[0]: first_team_id}  # fallback

    df_shots['team'] = df_shots['team_id'].map(shot_map)
    shots_on_target = df_shots[df_shots['Shots_on_Target'] == 1]['team'].value_counts().to_dict()
    shots_saved = df_shots[df_shots['Saved_shots'] == 1]['team'].value_counts().to_dict()
    total_shots = df_shots['team'].value_counts().to_dict()

    # === ✅ Goals: dynamic team mapping
    goal_teams = df_goals['team_id'].unique()
    if len(goal_teams) == 2:
        goal_map = {goal_teams[0]: first_team_id, goal_teams[1]: second_team_id}
    else:
        goal_map = {goal_teams[0]: first_team_id}  # fallback

    df_goals['team'] = df_goals['team_id'].map(goal_map)
    total_goals = df_goals['team'].value_counts().to_dict()

    # === Tackles
    df_tackles['team'] = df_tackles['team_id'].apply(lambda x: first_team_id if x == 1 else second_team_id)
    tackles = df_tackles['team'].value_counts().to_dict()

    # === Helper: fallback to 0
    def safe(stat, team): return stat.get(team, 0)

    # === Final Data Structure
    match_data = {
        "team1_id": first_team_id,
        "team2_id": second_team_id,
        "ball_possession": {
            first_team_id: safe(ball_possession, first_team_id),
            second_team_id: safe(ball_possession, second_team_id)
        },
        "corners": {
            first_team_id: safe(corners, first_team_id),
            second_team_id: safe(corners, second_team_id)
        },
        "free_kicks": {
            first_team_id: safe(free_kicks, first_team_id),
            second_team_id: safe(free_kicks, second_team_id)
        },
        "passes": {
            first_team_id: safe(passes, first_team_id),
            second_team_id: safe(passes, second_team_id)
        },
        "shirt_numbers": shirt_numbers,
        "shots_on_target": {
            first_team_id: safe(shots_on_target, first_team_id),
            second_team_id: safe(shots_on_target, second_team_id)
        },
        "shots_saved": {
            first_team_id: safe(shots_saved, first_team_id),
            second_team_id: safe(shots_saved, second_team_id)
        },
        "tackles": {
            first_team_id: safe(tackles, first_team_id),
            second_team_id: safe(tackles, second_team_id)
        },
        "total_goals": {
            first_team_id: safe(total_goals, first_team_id),
            second_team_id: safe(total_goals, second_team_id)
        },
        "total_shots": {
            first_team_id: safe(total_shots, first_team_id),
            second_team_id: safe(total_shots, second_team_id)
        }
    }

    # === Upload to Firebase
    db.collection("matches").document(match_id).set(match_data, merge=True)
    print("✅ Match summary uploaded successfully.")


# === Call the function ===
upload_match_summary(
    match_id="mIPqSIphxFeeix2gKpbB",
    first_team_id="VVC#214",
    second_team_id="SLK@321",
    passes_csv="/content/passes_metrics.csv",
    set_pieces_csv="/content/set_pieces_metrics.csv",
    shots_csv="/content/shots_metrics_fixed.csv",
    tackles_csv="/content/tackles_metrics.csv",
    goals_csv="/content/goals_metrics_fixed.csv"
)