# -*- coding: utf-8 -*-
"""Untitled74.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATe4e54fXVvrBuht1FEuSL4dsGkPXhha
"""

import pandas as pd

def generate_passes_metrics(csv_path, save=True, output_name="passes_metrics.csv"):
    df = pd.read_csv(csv_path)

    df['position'] = list(zip(df['position_x'], df['position_y']))
    df['pass_id'] = df.index + 1
    df['start_frame_num'] = df['frame_num'] - 150
    df['end_frame_num'] = df['frame_num'] + 150
    df['start_frame_num'] = df['start_frame_num'].clip(lower=0)
    df['end_frame_num'] = df['end_frame_num'].clip(lower=0)

    passes_metrics = df[[
        'shirt_num1',
        'team_id_1',
        'success',
        'fail',
        'pass_id',
        'position',
        'start_frame_num',
        'end_frame_num'
    ]]

    if save:
        passes_metrics.to_csv(output_name, index=False)

    return passes_metrics
generate_passes_metrics("/content/test_gui_passes_input_fixed.csv")

import pandas as pd
import numpy as np

def transform_passing_network_metrics(passes_csv, save=True, output_name="passing_network_metrics_fixed.csv"):
    df = pd.read_csv(passes_csv)
    df.sort_values(by='frame_num', inplace=True)

    network_data = []
    current_chain = []
    current_team = None
    current_type = None  # 'success' or 'fail'

    for _, row in df.iterrows():
        team = row['team_id_1']
        success = row['success']
        fail = row['fail']
        frame = row['frame_num']
        shirt_number = row['shirt_num1']
        pos_x = row['position_x']
        pos_y = row['position_y']

        # Determine pass type
        if success == 1 and fail == 0:
            pass_type = 'success'
        elif success == 0 and fail == 1:
            pass_type = 'fail'
        else:
            pass_type = None

        if pass_type:
            if current_team is None:
                current_team = team
                current_type = pass_type
                current_chain = [{
                    'frame': frame,
                    'shirt_number': shirt_number,
                    'position_x': pos_x,
                    'position_y': pos_y
                }]
            elif team == current_team and pass_type == current_type:
                current_chain.append({
                    'frame': frame,
                    'shirt_number': shirt_number,
                    'position_x': pos_x,
                    'position_y': pos_y
                })
            else:
                # Save previous chain
                if len(current_chain) > 0:
                    frames = [entry['frame'] for entry in current_chain]
                    shirt_numbers = [int(entry['shirt_number']) for entry in current_chain]
                    positions_x = [entry['position_x'] for entry in current_chain]
                    positions_y = [entry['position_y'] for entry in current_chain]

                    network_data.append({
                        'team_id': current_team,
                        'pass_type': current_type,
                        'number_of_passes': len(current_chain),
                        'start_frame_num': max(0, min(frames) - 150),
                        'end_frame_num': max(0, max(frames) + 150),
                        'position_x': np.mean(positions_x),
                        'position_y': np.mean(positions_y),
                        'shirt_number': shirt_numbers
                    })
                # Start new chain
                current_team = team
                current_type = pass_type
                current_chain = [{
                    'frame': frame,
                    'shirt_number': shirt_number,
                    'position_x': pos_x,
                    'position_y': pos_y
                }]
        else:
            # Save current chain if interrupted
            if len(current_chain) > 0:
                frames = [entry['frame'] for entry in current_chain]
                shirt_numbers = [int(entry['shirt_number']) for entry in current_chain]
                positions_x = [entry['position_x'] for entry in current_chain]
                positions_y = [entry['position_y'] for entry in current_chain]

                network_data.append({
                    'team_id': current_team,
                    'pass_type': current_type,
                    'number_of_passes': len(current_chain),
                    'start_frame_num': max(0, min(frames) - 150),
                    'end_frame_num': max(0, max(frames) + 150),
                    'position_x': np.mean(positions_x),
                    'position_y': np.mean(positions_y),
                    'shirt_number': shirt_numbers
                })
            # Reset chain
            current_team = None
            current_type = None
            current_chain = []

    # Final chain
    if len(current_chain) > 0:
        frames = [entry['frame'] for entry in current_chain]
        shirt_numbers = [int(entry['shirt_number']) for entry in current_chain]
        positions_x = [entry['position_x'] for entry in current_chain]
        positions_y = [entry['position_y'] for entry in current_chain]

        network_data.append({
            'team_id': current_team,
            'pass_type': current_type,
            'number_of_passes': len(current_chain),
            'start_frame_num': max(0, min(frames) - 150),
            'end_frame_num': max(0, max(frames) + 150),
            'position_x': np.mean(positions_x),
            'position_y': np.mean(positions_y),
            'shirt_number': shirt_numbers
        })

    # Output DataFrame
    network_df = pd.DataFrame(network_data)

    if save:
        network_df.to_csv(output_name, index=False)

    return network_df
transform_passing_network_metrics("/content/test_gui_passes_input_fixed.csv")

import pandas as pd

def transform_interceptions_metrics(passes_csv, save=True, output_name="interceptions_metrics_fixed.csv"):
    df = pd.read_csv(passes_csv)
    df.sort_values(by='frame_num', inplace=True)
    df.reset_index(drop=True, inplace=True)

    interceptions = []

    for i, row in df.iterrows():
        team = row['team_id_1']
        success = row['success']
        fail = row['fail']
        frame = row['frame_num']
        position = (row['position_x'], row['position_y'])

        # If this is a failed pass, track it as a ball loss
        if fail == 1 and success == 0:
            # Row 1: Player who lost the ball
            interceptions.append({
                'shirt_number': row['shirt_num1'],
                'team_id': team,
                'ball_loss': 1,
                'ball_recovery': 0,
                'position': position,
                'start_frame_num': max(0,frame - 150),
                'end_frame_num': max(0,frame + 150)
            })

            # Row 2: Find the first pass from the other team = interception
            next_by_opponent = df[(df['frame_num'] > frame) & (df['team_id_1'] != team)]
            if not next_by_opponent.empty:
                interceptor = next_by_opponent.iloc[0]
                interceptions.append({
                    'shirt_number': interceptor['shirt_num1'],
                    'team_id': interceptor['team_id_1'],
                    'ball_loss': 0,
                    'ball_recovery': 1,
                    'position': position,  # 👈 same position as the ball loss
                    'start_frame_num': max(0,interceptor['frame_num'] - 150),
                    'end_frame_num': max(0,interceptor['frame_num'] + 150)
                })

    df_interceptions = pd.DataFrame(interceptions)

    if save:
        df_interceptions.to_csv(output_name, index=False)

    return df_interceptions
transform_interceptions_metrics("/content/test_gui_passes_input_fixed.csv")

import pandas as pd


def tackles_metrics(csv_path, save=True, output_name="tackles_metrics.csv"):
    # Load the raw GUI data
    df = pd.read_csv(csv_path)

    # Combine x and y into a position tuple
    df['position'] = list(zip(df['position_x'], df['position_y']))

    # Compute start and end frame numbers
    df['start_frame_num'] = (df['frame_num'] - 150)
    df['end_frame_num'] = (df['frame_num'] + 150)
    df['start_frame_num'] = df['start_frame_num'].clip(lower=0)
    df['end_frame_num'] = df['end_frame_num'].clip(lower=0)

    # Use the true tackling player info from player_1
    df['shirt_number'] = df['shirt_number_1']
    df['team_id'] = df['team_id_1']
    df['tackling_success'] = df['success']
    df['tackling_failure'] = df['fail']

    # Create final tackles_metrics DataFrame
    tackles_metrics = df[[
        'shirt_number',
        'team_id',
        'tackling_success',
        'tackling_failure',
        'start_frame_num',
        'end_frame_num',
        'position'
    ]]
    if save:
        tackles_metrics.to_csv(output_name, index=False)

    return tackles_metrics

tackles_metrics("/content/test_gui_tackles_input_fixed.csv")

import pandas as pd

def dribble_metrics(csv_path, save=True, output_name="dribble_metrics_success_only.csv"):
    df = pd.read_csv(csv_path)

    # Create position tuple and frame range
    df['position'] = list(zip(df['position_x'], df['position_y']))
    df['start_frame_num'] = (df['frame_num'] - 150)
    df['end_frame_num'] = (df['frame_num'] + 150)
    df['start_frame_num'] = df['start_frame_num'].clip(lower=0)
    df['end_frame_num'] = df['end_frame_num'].clip(lower=0)

    records = []

    for _, row in df.iterrows():

        dribbler_row = {
            'shirt_number': row['shirt_number_1'],
            'team_id': row['team_id_1'],
            'dribble_success': row['success'],
            'dribble_failure': row['fail'],
            'dribbled_past': 0,
            'start_frame_num': row['start_frame_num'],
            'end_frame_num': row['end_frame_num'],
            'position': row['position']
        }
        records.append(dribbler_row)

        if row['success'] == 1:
            dribbled_row = {
                'shirt_number': row['shirt_number_2'],
                'team_id': row['team_id_2'],
                'dribble_success': 0,
                'dribble_failure': 0,
                'dribbled_past': 1,
                'start_frame_num': row['start_frame_num'],
                'end_frame_num': row['end_frame_num'],
                'position': row['position']
            }
            records.append(dribbled_row)

    result_df = pd.DataFrame(records)

    if save:
        result_df.to_csv(output_name, index=False)

    return result_df
dribble_metrics("/content/large_dribble_gui_output.csv")

def transform_aerial_metrics(csv_path, save=True, output_name="aerial_duels_fixed.csv"):
    df = pd.read_csv(csv_path)
    df['position'] = list(zip(df['position_x'], df['position_y']))
    df['start_frame_num'] = df['frame_num'] - 150
    df['end_frame_num'] = df['frame_num'] + 150
    df['start_frame_num'] = df['start_frame_num'].clip(lower=0)
    df['end_frame_num'] = df['end_frame_num'].clip(lower=0)

    records = []
    for _, row in df.iterrows():
        start_frame = row['start_frame_num']
        end_frame = row['end_frame_num']
        pos = row['position']

        records.append({
            'shirt_number': row['shirt_number_1'],
            'team_id': row['team_id_1'],
            'aerial_success': row['success'],
            'aerial_failure': row['fail'],
            'start_frame_num': start_frame,
            'end_frame_num': end_frame,
            'position': pos
        })
        records.append({
            'shirt_number': row['shirt_number_2'],
            'team_id': row['team_id_2'],
            'aerial_success': row['fail'],
            'aerial_failure': row['success'],
            'start_frame_num': start_frame,
            'end_frame_num': end_frame,
            'position': pos
        })

    result_df = pd.DataFrame(records)
    if save:
        result_df.to_csv(output_name, index=False)
    return result_df

transform_aerial_metrics("/content/aerial_duels_sample.csv")

def transform_ground_metrics(csv_path, save=True, output_name="ground_duels_fixed.csv"):
    df = pd.read_csv(csv_path)
    df['position'] = list(zip(df['position_x'], df['position_y']))
    df['start_frame_num'] = df['frame_num'] - 150
    df['end_frame_num'] = df['frame_num'] + 150
    df['start_frame_num'] = df['start_frame_num'].clip(lower=0)
    df['end_frame_num'] = df['end_frame_num'].clip(lower=0)

    records = []
    for _, row in df.iterrows():
        start_frame = row['start_frame_num']
        end_frame = row['end_frame_num']
        pos = row['position']

        records.append({
            'shirt_number': row['shirt_number_1'],
            'team_id': row['team_id_1'],
            'ground_success': row['success'],
            'ground_failure': row['fail'],
            'start_frame_num': start_frame,
            'end_frame_num': end_frame,
            'position': pos
        })
        records.append({
            'shirt_number': row['shirt_number_2'],
            'team_id': row['team_id_2'],
            'ground_success': row['fail'],
            'ground_failure': row['success'],
            'start_frame_num': start_frame,
            'end_frame_num': end_frame,
            'position': pos
        })

    result_df = pd.DataFrame(records)
    if save:
        result_df.to_csv(output_name, index=False)
    return result_df
transform_ground_metrics("/content/test_gui_ground_input_fixed.csv")

import pandas as pd

def set_pieces_metrics(csv_path, save=True, output_name="set_pieces_metrics.csv"):
    df = pd.read_csv(csv_path)

    # Combine x and y into a tuple
    df['position'] = list(zip(df['position_x'], df['position_y']))

    # Frame range
    df['start_frame_num'] = df['frame_num'] - 150
    df['end_frame_num'] = df['frame_num'] + 150
    df['start_frame_num'] = df['start_frame_num'].clip(lower=0)
    df['end_frame_num'] = df['end_frame_num'].clip(lower=0)
    # Final format
    set_pieces_metrics = df[[
        'shirt_num1',
        'team_id_1',
        'throw',
        'corner',
        'penalty',
        'direct kick',
        'indirect kick',
        'start_frame_num',
        'end_frame_num',
        'position'
    ]]

    if save:
        set_pieces_metrics.to_csv(output_name, index=False)

    return set_pieces_metrics

set_pieces_metrics("/content/set_pieces_gui_format.csv")

import pandas as pd

def transform_goals_metrics(shots_csv, passes_csv, save=True, output_name="goals_metrics_fixed.csv"):
    # Load the shots and passes data
    shots_df = pd.read_csv(shots_csv)
    passes_df = pd.read_csv(passes_csv)

    # Create position tuple and extract frame_num
    shots_df['position'] = list(zip(shots_df['position_x'], shots_df['position_y']))
    shots_df['frame_num'] = shots_df['frame_nur']
    passes_df.sort_values(by='frame_num', inplace=True)
    passes_df.reset_index(drop=True, inplace=True)

    rows = []

    for _, shot in shots_df.iterrows():
        shot_frame = shot['frame_num']
        shot_team = shot['team_id_1']

        # Identify if it's a valid normal goal
        is_goal = (
            shot['On Target'] == 1 and
            shot['Saved'] == 0 and
            shot['Blocked'] == 0 and
            shot['Penalty'] == 0 and
            shot['Own Goal'] == 0
        )

        if not is_goal:
            continue

        # --- Row 1: Goal Scorer
        rows.append({
            'shirt_number': shot['shirt_num1'],
            'team_id': shot['team_id_1'],
            'Goal': 1,
            'Assist': 0,
            'penalties': shot['Penalty'],
            'own_goals': shot['Own Goal'],
            'position': (shot['position_x'], shot['position_y']),
            'start_frame_num': max(0,shot_frame - 150),
            'end_frame_num': max(0,shot_frame + 150)
        })

        # --- Row 2: Assist Maker (last successful pass before the shot)
        key_pass = passes_df[
            (passes_df['frame_num'] < shot_frame) &
            (passes_df['team_id_1'] == shot_team) &
            (passes_df['success'] == 1)
        ]

        if not key_pass.empty:
            last_pass = key_pass.iloc[-1]
            rows.append({
                'shirt_number': last_pass['shirt_num1'],
                'team_id': last_pass['team_id_1'],
                'Goal': 0,
                'Assist': 1,
                'penalties': 0,
                'own_goals': 0,
                'position': (last_pass['position_x'], last_pass['position_y']),
                'start_frame_num': max(0,last_pass['frame_num'] - 150),
                'end_frame_num': max(0,last_pass['frame_num'] + 150)
            })

    result_df = pd.DataFrame(rows)

    if save:
        result_df.to_csv(output_name, index=False)

    return result_df

transform_goals_metrics("/content/test_gui_shots_input.csv","/content/test_gui_passes_input_fixed.csv")

import pandas as pd

def transform_shots_metrics(shots_csv, passes_csv, save=True, output_name="shots_metrics_fixed.csv"):
    shots_df = pd.read_csv(shots_csv)
    passes_df = pd.read_csv(passes_csv)

    shots_df['position'] = list(zip(shots_df['position_x'], shots_df['position_y']))
    shots_df['frame_num'] = shots_df['frame_nur']

    passes_df.sort_values(by='frame_num', inplace=True)
    passes_df.reset_index(drop=True, inplace=True)

    output_rows = []

    for _, shot in shots_df.iterrows():
        shot_frame = shot['frame_num']
        shot_team = shot['team_id_1']

        # --- ROW 1: Shooter
        output_rows.append({
            'shirt_number': shot['shirt_num1'],
            'team_id': shot['team_id_1'],
            'Key_passes': 0,
            'Shots_on_Target': shot['On Target'],
            'Shots_off_Target': shot['Off Target'],
            'Saved_shots': shot['Saved'],
            'Blocked_shots': shot['Blocked'],
            'Clearances': 0,
            'saves': 0,
            'penalties': shot['Penalty'],
            'position': (shot['position_x'], shot['position_y']),
            'start_frame_num': max(0,shot_frame - 150),
            'end_frame_num': max(0,shot_frame + 150)
        })

        # --- ROW 2: Key Passer
        key_pass = passes_df[
            (passes_df['frame_num'] < shot_frame) &
            (passes_df['team_id_1'] == shot_team) &
            (passes_df['success'] == 1)
        ]
        if not key_pass.empty:
            last_pass = key_pass.iloc[-1]
            output_rows.append({
                'shirt_number': last_pass['shirt_num1'],
                'team_id': last_pass['team_id_1'],
                'Key_passes': 1,
                'Shots_on_Target': 0,
                'Shots_off_Target': 0,
                'Saved_shots': 0,
                'Blocked_shots': 0,
                'Clearances': 0,
                'saves': 0,
                'penalties': 0,
                'position': (last_pass['position_x'], last_pass['position_y']),
                'start_frame_num': max(0, last_pass['frame_num'] - 150),
                'end_frame_num': max(0, last_pass['frame_num'] + 150)
            })

        # --- ROW 3: Clearance or Save (optional)
        label = None
        if shot['Blocked'] == 1 and shot['Saved'] == 0:
            label = 'Clearances'
        elif shot['Saved'] == 1 and shot['Blocked'] == 0:
            label = 'saves'

        if label:
            next_pass = passes_df[passes_df['frame_num'] > shot_frame]
            if not next_pass.empty:
                first_after = next_pass.iloc[0]
                output_rows.append({
                    'shirt_number': first_after['shirt_num1'],
                    'team_id': first_after['team_id_1'],
                    'Key_passes': 0,
                    'Shots_on_Target': 0,
                    'Shots_off_Target': 0,
                    'Saved_shots': 0,
                    'Blocked_shots': 0,
                    'Clearances': 1 if label == 'Clearances' else 0,
                    'saves': 1 if label == 'saves' else 0,
                    'penalties': 0,
                    'position': (first_after['position_x'], first_after['position_y']),
                    'start_frame_num': max(0,first_after['frame_num'] - 150),
                    'end_frame_num': max(0,first_after['frame_num'] + 150)
                })

    result_df = pd.DataFrame(output_rows)

    if save:
        result_df.to_csv(output_name, index=False)

    return result_df

transform_shots_metrics("/content/test_gui_shots_input.csv","/content/test_gui_passes_input_fixed.csv")

import pandas as pd

def transform_passing_network_metrics(passes_csv, save=True, output_name="passing_network_metrics.csv"):
    df = pd.read_csv(passes_csv)
    df.sort_values(by='frame_num', inplace=True)

    network_data = []
    current_chain = []
    current_shirts = []
    current_team = None
    current_type = None  # 'success' or 'fail'

    for _, row in df.iterrows():
        team = row['team_id_1']
        success = row['success']
        fail = row['fail']
        frame = row['frame_num']
        shirt = row['shirt_num1']

        # Identify pass type
        if success == 1 and fail == 0:
            pass_type = 'success'
        elif success == 0 and fail == 1:
            pass_type = 'fail'
        else:
            pass_type = None

        if pass_type:
            if current_team is None:
                current_team = team
                current_type = pass_type
                current_chain = [frame]
                current_shirts = [shirt]
            elif team == current_team and pass_type == current_type:
                current_chain.append(frame)
                current_shirts.append(shirt)
            else:
                # Save current chain before resetting
                network_data.append({
                    'team_id': current_team,
                    'pass_type': current_type,
                    'number_of_passes': len(current_chain),
                    'start_frame_num': current_chain[0] - 150,
                    'end_frame_num': current_chain[-1] + 150,
                    'shirt_numbers': [int(s) for s in current_shirts]
                })
                # Start new chain
                current_team = team
                current_type = pass_type
                current_chain = [frame]
                current_shirts = [shirt]
        else:
            # Save invalid current chain before skipping
            if len(current_chain) > 0:
                network_data.append({
                    'team_id': current_team,
                    'pass_type': current_type,
                    'number_of_passes': len(current_chain),
                    'start_frame_num': current_chain[0] - 150,
                    'end_frame_num': current_chain[-1] + 150,
                    'shirt_numbers': [int(s) for s in current_shirts]
                })
                current_team = None
                current_type = None
                current_chain = []
                current_shirts = []

    # Save last chain if it exists
    if len(current_chain) > 0:
        network_data.append({
            'team_id': current_team,
            'pass_type': current_type,
            'number_of_passes': len(current_chain),
            'start_frame_num': current_chain[0] - 150,
            'end_frame_num': current_chain[-1] + 150,
            'shirt_numbers': [int(s) for s in current_shirts]
        })

    network_df = pd.DataFrame(network_data)

    if save:
        network_df.to_csv(output_name, index=False)

    return network_df

transform_passing_network_metrics("/content/test_gui_passes_input_fixed.csv")